####
GET  http://localhost:3001/api/auth/google/callback


### post method

POST http://localhost:3001/api/Operator
Content-Type: application/json

{
  "Name": "Mdarify123",
  "Email": "john45134-112343.doe@gmail.com",
  "Password": "securePass123",
  "PhoneNumber": "21234567890",
  "Provider": "google",
  "userType": "Operator"
}


POST http://localhost:3001/api/Client
Content-Type: application/json

{
  "Name": "Mdarify123",
  "Email": "john45134-112343.doe@gmail.com",
  "Password": "securePass123",
  "PhoneNumber": "21234567890",
  "Provider": "google",
  "userType": "Operator"
}


### Create Experience
POST http://localhost:3001/api/experiences
Content-Type: application/json

{
  "Title": "New Experience",
  "Description": "An exciting new experience",
  "Category": "Adventure",
  "Location": "City, Country",
  "Price": "100",
  "Currency": "USD",
  "Location": {
      "City": "Denver",
      "Country": "USA",
      "Coordinates": {
        "lat": 39.7392,
        "lng": -104.9903
      }
  },
  "AvailabilityCalendar": "2024-11-25",
  "Images": ["image1.jpg", "image2.jpg"],
  "Videos": ["video1.mp4"],
  "SustainabilityPractices": "Eco-friendly",
  "operatorId": "89883e8e-5c4e-4d1f-8956-1c8e3ae11a3e"
}

### Get All Experiences
GET http://localhost:3001/api/experiences

### Get Experience by ID
GET http://localhost:3001/api/experiences/737853c7-2785-4653-9b33-0f67827c20f2

### Update Experience
PUT http://localhost:3001/api/experiences/737853c7-2785-4653-9b33-0f67827c20f2
Content-Type: application/json

{
  "Price": 1250.00,
  "Currency": "USD"
}

### Delete Experience
DELETE http://localhost:3001/api/experiences/6298995b-084c-42c3-b44a-1d4b140ac982


### GET ALL EXPERINECES CREATED BY SPECIFIC OPERATOR

GET http://localhost:3001/api/experiences/operator/89883e8e-5c4e-4d1f-8956-1c8e3ae11a3e


### GET ALL EXPERIENCES BETWEEN TWO DATES

GET http://localhost:3001/api/experiences/date-range?startDate=2024-01-01T00:00:00Z&endDate=2024-11-31T23:59:59Z HTTP/1.1
Accept: application/json
